language: go
sudo: required
go:
  - 1.19

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.9.0

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sed -i -e 's/golang/golang:'"$TRAVIS_GO_VERSION"'/' docker-compose.yml
  - docker --version
  - docker-compose --version

script: make test-build